version: "2"

services:

  jenkins-server:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      CASC_JENKINS_CONFIG: /var/jenkins_home/casc_configs
    ports:
      - 8080:8080/tcp
    volumes:
      - jenkins_data:/var/lib/jenkins_home:rw
      - ./config/jenkins/casc:/var/jenkins_home/casc_configs:rw

volumes:
  jenkins_data: {}
