pipeline {
  agent any
  triggers {
    GenericTrigger(
     genericVariables: [
      [key: 'BRANCH_WH', value: '$.workflow_run.head_branch']
     ],

     //causeString: 'Triggered on $BRANCH_WH',

     token: 'dummy',
     tokenCredentialId: '',

     printContributedVariables: true,
     printPostContent: true,

     silentResponse: false,

     //regexpFilterText: '$BRANCH_WH',
     //regexpFilterExpression: 'refs/heads/' + BRANCH_NAME
    )
  }
  stages {

    stage('Checkout') {
      steps {
        script {
          def scmVars = checkout(
            [
              $class: 'GitSCM', 
              branches: [
                [name: "*/${BRANCH_WH}"]
              ], 
              doGenerateSubmoduleConfigurations: false, 
              extensions: [
                [
                  $class: 'CleanBeforeCheckout',
                  deleteUntrackedNestedRepositories: true
                ],
                [
                  $class: 'CleanCheckout',
                  deleteUntrackedNestedRepositories: true
                ],
                [
                  $class: 'CloneOption',
                  shallow: true,
                  depth: 1,
                  noTags: false
                ]
              ],
              submoduleCfg: [],
              //userRemoteConfigs: [
              //  [
              //    credentialsId: 'github-default-ssh', 
              //    url: 'git@github.com:luismiguelsaez/cicd-playground.git'
              //  ]
              //]
            ]
          )
        }
      }
    }

    stage('Debugging build') {
      steps {
        echo "Building branch: $BRANCH_WH"
      }
    }

  }
}